import AppNavigation from "@/components/AppNavigation";
import AuthProvider from "@/components/AuthProvider";
import "@/styles/index.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>
          <AppNavigation />

          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
